# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


source 'https://github.com/CocoaPods/Specs.git'

target 'FinalProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FinalProject

  target 'FinalProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FinalProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
end
